/************************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.3.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 *
 * Generated Date: 2019年12月9日
 ***********************************************************************************************/

#include "sensor_interface.h"

#define MAX_MASSAGE_SIZE 256

//
// Callback function declarations and DigitalTwin writable (from service side) properties for this interface
//

static void SensorInterface_Property_WifimacCallback(const DIGITALTWIN_CLIENT_PROPERTY_UPDATE* dtClientPropertyUpdate, void* userInterfaceContext);

static void SensorInterface_Property_LanmacCallback(const DIGITALTWIN_CLIENT_PROPERTY_UPDATE* dtClientPropertyUpdate, void* userInterfaceContext);

//
//  Callback function declarations and DigitalTwin command names for this interface.
//

static void SensorInterface_Command_RebootCallback(const DIGITALTWIN_CLIENT_COMMAND_REQUEST* commandRequest, DIGITALTWIN_CLIENT_COMMAND_RESPONSE* commandResponse, void* userInterfaceContext);

//
// Application state associated with this interface.
// It contains the DIGITALTWIN_INTERFACE_CLIENT_HANDLE used for responses in callbacks along with properties set
// and representations of the property update and command callbacks invoked on given interface
//
typedef struct SENSOR_INTERFACE_STATE_TAG
{
    DIGITALTWIN_INTERFACE_CLIENT_HANDLE interfaceClientHandle;

    char* wifimac;

    char* lanmac;

} SENSOR_INTERFACE_STATE;

static SENSOR_INTERFACE_STATE appState;

// Callback function to process the command "reboot".
void SensorInterface_Command_RebootCallback(const DIGITALTWIN_CLIENT_COMMAND_REQUEST* commandRequest, DIGITALTWIN_CLIENT_COMMAND_RESPONSE* commandResponse, void* userInterfaceContext)
{
    SENSOR_INTERFACE_STATE* interfaceState = (SENSOR_INTERFACE_STATE*)userInterfaceContext;
    LogInfo("SENSOR_INTERFACE: reboot command invoked.");
    LogInfo("SENSOR_INTERFACE: reboot request payload=<%.*s>, context=<%p>", (int)commandRequest->requestDataLen, commandRequest->requestData, interfaceState);

    // Invoke device command here
    unsigned int statusCode = 200;

    DIGITALTWIN_COMMAND_RESULT commandResult = Sensor_Command_Reboot(&statusCode);

    if (commandResult == DIGITALTWIN_COMMAND_OK)
    {
        DigitalTwinClientHelper_SetCommandResponse(commandResponse, NULL, statusCode);

    }
    else
    {
        LogError("Failed to execute reboot command");
        char* errorResponse = "\"Failed to execute reboot command\"";
        DigitalTwinClientHelper_SetCommandResponse(commandResponse, errorResponse, statusCode);
    }

}

// DigitalTwinSample_ProcessCommandUpdate receives commands from the server.  This implementation acts as a simple dispatcher
// to the functions to perform the actual processing.
void SensorInterface_ProcessCommandUpdate(const DIGITALTWIN_CLIENT_COMMAND_REQUEST* dtCommandRequest, DIGITALTWIN_CLIENT_COMMAND_RESPONSE* dtCommandResponse, void* userInterfaceContext)
{
    if (strcmp(dtCommandRequest->commandName, SensorInterface_RebootCommand) == 0)
    {
        SensorInterface_Command_RebootCallback(dtCommandRequest, dtCommandResponse, userInterfaceContext);
        return;
    }

    // If the command is not implemented by this interface, by convention we return a 501 error to server.
    LogError("SENSOR_INTERFACE: Command name <%s> is not associated with this interface", dtCommandRequest->commandName);
    (void)DigitalTwinClientHelper_SetCommandResponse(dtCommandResponse, "\"Requested command not implemented on this interface\"", 501);
}

// SensorInterface_PropertyCallback is invoked when a property is updated (or failed) going to server.
// ALL property callbacks will be routed to this function and just have the userContextCallback set to the propertyName.
// Product code will potentially have context stored in this userContextCallback.
static void SensorInterface_PropertyCallback(DIGITALTWIN_CLIENT_RESULT digitalTwinReportedStatus, void* userContextCallback)
{
    if (digitalTwinReportedStatus == DIGITALTWIN_CLIENT_OK)
    {
        ReportProperty_Succeeded_Callback("Sensor", (const char*)userContextCallback);
        LogInfo("SENSOR_INTERFACE: Updating property=<%s> succeeded", (const char*)userContextCallback);
    }
    else
    {
        ReportProperty_Error_Callback("Sensor", (const char*)userContextCallback);
        LogError("SENSOR_INTERFACE: Updating property=<%s> failed, error=<%s>", (const char*)userContextCallback, MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, digitalTwinReportedStatus));
    }
}

// Processes a property update, which the server initiated, for 'wifimac' property.
static void SensorInterface_Property_WifimacCallback(const DIGITALTWIN_CLIENT_PROPERTY_UPDATE* dtClientPropertyUpdate, void* userInterfaceContext)
{
    SENSOR_INTERFACE_STATE* interfaceState = (SENSOR_INTERFACE_STATE*)userInterfaceContext;

    LogInfo("SENSOR_INTERFACE: wifimac property invoked...");
    LogInfo("SENSOR_INTERFACE: wifimac data=<%.*s>", (int)dtClientPropertyUpdate->propertyDesiredLen, dtClientPropertyUpdate->propertyDesired);

    DIGITALTWIN_CLIENT_PROPERTY_RESPONSE propertyResponse;

    // Version of this structure for C SDK.
    propertyResponse.version = DIGITALTWIN_CLIENT_PROPERTY_RESPONSE_VERSION_1;
    propertyResponse.responseVersion = dtClientPropertyUpdate->desiredVersion;

    if (interfaceState->wifimac != NULL)
    {
        free(interfaceState->wifimac);
    }

    interfaceState->wifimac = (char*)malloc(dtClientPropertyUpdate->propertyDesiredLen + 1);
    if (interfaceState->wifimac == NULL)
    {
        LogError("SENSOR_INTERFACE: Out of memory updating wifimac...");

        // Indicates failure
        propertyResponse.statusCode = 500;
        // Optional additional human readable information about status.
        propertyResponse.statusDescription = "Out of memory";
    }
    else
    {
        strncpy(interfaceState->wifimac, (char*)dtClientPropertyUpdate->propertyDesired, dtClientPropertyUpdate->propertyDesiredLen);
        interfaceState->wifimac[dtClientPropertyUpdate->propertyDesiredLen] = 0;

        LogInfo("SENSOR_INTERFACE: Updating wifimac property with new desired value <%s> ...", dtClientPropertyUpdate->propertyDesired);
        bool updateResult = Sensor_Property_WifimacCallback(interfaceState->wifimac);

        if (updateResult)
        {
            propertyResponse.statusCode = 200;
            propertyResponse.statusDescription = "wifimac property is updated successfully";
        }
        else
        {
            LogError("SENSOR_INTERFACE: failed to update property wifimac...");

            propertyResponse.statusCode = 500;
            propertyResponse.statusDescription = "failed to update writable property";
        }
    }

    // DigitalTwin_InterfaceClient_ReportPropertyAsync takes the DIGITALTWIN_CLIENT_PROPERTY_RESPONSE and returns information back to service.
    DIGITALTWIN_CLIENT_RESULT result = DigitalTwin_InterfaceClient_ReportPropertyAsync(appState.interfaceClientHandle, SensorInterface_WifimacProperty, 
        (const char*)dtClientPropertyUpdate->propertyDesired, &propertyResponse,
        SensorInterface_PropertyCallback, SensorInterface_WifimacProperty);
    if (result != DIGITALTWIN_CLIENT_OK)
    {
        LogError("SENSOR_INTERFACE: DigitalTwin_InterfaceClient_ReportPropertyAsync for wifimac failed, error=<%s>", MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, result));
    }
    else
    {
        LogInfo("SENSOR_INTERFACE: Successfully queued property update for wifimac");
    }
}

// Processes a property update, which the server initiated, for 'lanmac' property.
static void SensorInterface_Property_LanmacCallback(const DIGITALTWIN_CLIENT_PROPERTY_UPDATE* dtClientPropertyUpdate, void* userInterfaceContext)
{
    SENSOR_INTERFACE_STATE* interfaceState = (SENSOR_INTERFACE_STATE*)userInterfaceContext;

    LogInfo("SENSOR_INTERFACE: lanmac property invoked...");
    LogInfo("SENSOR_INTERFACE: lanmac data=<%.*s>", (int)dtClientPropertyUpdate->propertyDesiredLen, dtClientPropertyUpdate->propertyDesired);

    DIGITALTWIN_CLIENT_PROPERTY_RESPONSE propertyResponse;

    // Version of this structure for C SDK.
    propertyResponse.version = DIGITALTWIN_CLIENT_PROPERTY_RESPONSE_VERSION_1;
    propertyResponse.responseVersion = dtClientPropertyUpdate->desiredVersion;

    if (interfaceState->lanmac != NULL)
    {
        free(interfaceState->lanmac);
    }

    interfaceState->lanmac = (char*)malloc(dtClientPropertyUpdate->propertyDesiredLen + 1);
    if (interfaceState->lanmac == NULL)
    {
        LogError("SENSOR_INTERFACE: Out of memory updating lanmac...");

        // Indicates failure
        propertyResponse.statusCode = 500;
        // Optional additional human readable information about status.
        propertyResponse.statusDescription = "Out of memory";
    }
    else
    {
        strncpy(interfaceState->lanmac, (char*)dtClientPropertyUpdate->propertyDesired, dtClientPropertyUpdate->propertyDesiredLen);
        interfaceState->lanmac[dtClientPropertyUpdate->propertyDesiredLen] = 0;

        LogInfo("SENSOR_INTERFACE: Updating lanmac property with new desired value <%s> ...", dtClientPropertyUpdate->propertyDesired);
        bool updateResult = Sensor_Property_LanmacCallback(interfaceState->lanmac);

        if (updateResult)
        {
            propertyResponse.statusCode = 200;
            propertyResponse.statusDescription = "lanmac property is updated successfully";
        }
        else
        {
            LogError("SENSOR_INTERFACE: failed to update property lanmac...");

            propertyResponse.statusCode = 500;
            propertyResponse.statusDescription = "failed to update writable property";
        }
    }

    // DigitalTwin_InterfaceClient_ReportPropertyAsync takes the DIGITALTWIN_CLIENT_PROPERTY_RESPONSE and returns information back to service.
    DIGITALTWIN_CLIENT_RESULT result = DigitalTwin_InterfaceClient_ReportPropertyAsync(appState.interfaceClientHandle, SensorInterface_LanmacProperty, 
        (const char*)dtClientPropertyUpdate->propertyDesired, &propertyResponse,
        SensorInterface_PropertyCallback, SensorInterface_LanmacProperty);
    if (result != DIGITALTWIN_CLIENT_OK)
    {
        LogError("SENSOR_INTERFACE: DigitalTwin_InterfaceClient_ReportPropertyAsync for lanmac failed, error=<%s>", MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, result));
    }
    else
    {
        LogInfo("SENSOR_INTERFACE: Successfully queued property update for lanmac");
    }
}

// SensorInterface_ProcessPropertyUpdate receives updated properties from the server.  This implementation
// acts as a simple dispatcher to the functions to perform the actual processing.
static void SensorInterface_ProcessPropertyUpdate(const DIGITALTWIN_CLIENT_PROPERTY_UPDATE* dtClientPropertyUpdate, void* userInterfaceContext)
{
    if (strcmp(dtClientPropertyUpdate->propertyName, SensorInterface_WifimacProperty) == 0)
    {
        SensorInterface_Property_WifimacCallback(dtClientPropertyUpdate, userInterfaceContext);
        return;
    }

    if (strcmp(dtClientPropertyUpdate->propertyName, SensorInterface_LanmacProperty) == 0)
    {
        SensorInterface_Property_LanmacCallback(dtClientPropertyUpdate, userInterfaceContext);
        return;
    }

    // If the property is not implemented by this interface, presently we only record a log message but do not have a mechanism to report back to the service
    LogError("SENSOR_INTERFACE: Property name <%s> is not associated with this interface", dtClientPropertyUpdate->propertyName);
}

// SensorInterface_TelemetryCallback is invoked when a DigitalTwin telemetry message is either successfully delivered to the service or else fails.
static void SensorInterface_TelemetryCallback(DIGITALTWIN_CLIENT_RESULT digitalTwinTelemetryStatus, void* userContextCallback)
{
    if (digitalTwinTelemetryStatus == DIGITALTWIN_CLIENT_OK)
    {
        SendTelemetry_Succeeded_Callback("Sensor", (const char*)userContextCallback);
        LogInfo("SENSOR_INTERFACE: DigitalTwin successfully delivered telemetry message for <%s>", (const char*)userContextCallback);
    }
    else
    {
        SendTelemetry_Error_Callback("Sensor", (const char*)userContextCallback);
        LogError("SENSOR_INTERFACE: DigitalTwin failed to deliver telemetry message for <%s>, error=<%s> ", (const char*)userContextCallback, MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, digitalTwinTelemetryStatus));
    }
}

// SendTelemetry is a helper function which is periodically invoked by the caller to send telemetry
DIGITALTWIN_CLIENT_RESULT SensorInterface_SendTelemetry_Internal(DIGITALTWIN_INTERFACE_CLIENT_HANDLE interfaceHandle, const char* telemetryName, const char* telemetryData)
{
    DIGITALTWIN_CLIENT_RESULT result;

    result = DigitalTwin_InterfaceClient_SendTelemetryAsync(interfaceHandle, telemetryName, telemetryData,
        SensorInterface_TelemetryCallback, (void*)telemetryName);

    if (result != DIGITALTWIN_CLIENT_OK)
    {
        LogError("SENSOR_INTERFACE:: DigitalTwin_InterfaceClient_SendTelemetryAsync failed for sending %s", telemetryName);
    }
    else
    {
        LogInfo("SENSOR_INTERFACE:: DigitalTwin_InterfaceClient_SendTelemetryAsync successfully sent %s", telemetryName);
    }

    DigitalTwinClientHelper_Check();
    return result;
}

DIGITALTWIN_CLIENT_RESULT SensorInterface_Telemetry_SendAll()
{
    DIGITALTWIN_CLIENT_RESULT result;

    // NOTE: Future versions of SDK will support ability to send multiple telemetries in a single
    // send.  For now, one at a time is sufficient albeit less efficient.
    if (((result = SensorInterface_Telemetry_SendCpuusage()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = SensorInterface_Telemetry_SendGpuusage()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = SensorInterface_Telemetry_SendMemoryusage()) != DIGITALTWIN_CLIENT_OK) )

    {
        LogError("SENSOR_INTERFACE: failed to send telemetries");
    }
    else
    {
        LogInfo("SENSOR_INTERFACE: Queuing of all telemetries to be sent has succeeded");
    }

    return result;
}

DIGITALTWIN_CLIENT_RESULT SensorInterface_Telemetry_SendCpuusage()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("SENSOR_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (Sensor_SerializeCpuusageTelemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return SensorInterface_SendTelemetry_Internal(appState.interfaceClientHandle, SensorInterface_CpuusageTelemetry, payloadBuffer);
    }
    else
    {
        LogError("SENSOR_INTERFACE: serialize telemetry message cpuusage failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT SensorInterface_Telemetry_SendGpuusage()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("SENSOR_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (Sensor_SerializeGpuusageTelemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return SensorInterface_SendTelemetry_Internal(appState.interfaceClientHandle, SensorInterface_GpuusageTelemetry, payloadBuffer);
    }
    else
    {
        LogError("SENSOR_INTERFACE: serialize telemetry message gpuusage failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT SensorInterface_Telemetry_SendMemoryusage()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("SENSOR_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (Sensor_SerializeMemoryusageTelemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return SensorInterface_SendTelemetry_Internal(appState.interfaceClientHandle, SensorInterface_MemoryusageTelemetry, payloadBuffer);
    }
    else
    {
        LogError("SENSOR_INTERFACE: serialize telemetry message memoryusage failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

// SensorInterface_InterfaceRegisteredCallback is invoked when this interface
// is successfully or unsuccessfully registered with the service, and also when the interface is deleted.
static void SensorInterface_InterfaceRegisteredCallback(DIGITALTWIN_CLIENT_RESULT dtInterfaceStatus, void* userInterfaceContext)
{
    LogInfo("SensorInterface_InterfaceRegisteredCallback with status=<%s>, userContext=<%p>", MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, dtInterfaceStatus), userInterfaceContext);
    if (dtInterfaceStatus == DIGITALTWIN_CLIENT_OK)
    {
        // Once the interface is registered, send our reported properties to the service.  
        // It *IS* safe to invoke most DigitalTwin API calls from a callback thread like this, though it 
        // is NOT safe to create/destroy/register interfaces now.
        LogInfo("SENSOR_INTERFACE: Interface successfully registered.");
    }
    else if (dtInterfaceStatus == DIGITALTWIN_CLIENT_ERROR_INTERFACE_UNREGISTERING)
    {
        // Once an interface is marked as unregistered, it cannot be used for any DigitalTwin SDK calls.
        LogInfo("SENSOR_INTERFACE: Interface received unregistering callback.");
    }
    else
    {
        LogError("SENSOR_INTERFACE: Interface received failed, status=<%s>.", MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, dtInterfaceStatus));
    }
}

//
// Create DigitalTwin interface client handle
//
DIGITALTWIN_INTERFACE_CLIENT_HANDLE SensorInterface_Create()
{
    DIGITALTWIN_INTERFACE_CLIENT_HANDLE interfaceHandle;
    DIGITALTWIN_CLIENT_RESULT result;

    memset(&appState, 0, sizeof(SENSOR_INTERFACE_STATE));

    if ((result = DigitalTwin_InterfaceClient_Create(SensorInterfaceId,  SensorInterfaceInstanceName, SensorInterface_InterfaceRegisteredCallback, (void*)&appState, &interfaceHandle)) != DIGITALTWIN_CLIENT_OK)
    {
        LogError("SENSOR_INTERFACE: Unable to allocate interface client handle for interfaceId=<%s>, interfaceInstanceName=<%s>, error=<%s>", SensorInterfaceId, SensorInterfaceInstanceName, MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, result));
        interfaceHandle = NULL;
    }

    else if ((result = DigitalTwin_InterfaceClient_SetPropertiesUpdatedCallback(interfaceHandle, SensorInterface_ProcessPropertyUpdate)) != DIGITALTWIN_CLIENT_OK)
    {
        LogError("SENSOR_INTERFACE: DigitalTwin_InterfaceClient_SetPropertiesUpdatedCallback failed. error=<%s>", MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, result));
        SensorInterface_Close(interfaceHandle);
        interfaceHandle = NULL;
    }

    else if ((result = DigitalTwin_InterfaceClient_SetCommandsCallback(interfaceHandle, SensorInterface_ProcessCommandUpdate)) != DIGITALTWIN_CLIENT_OK)
    {
        LogError("SENSOR_INTERFACE: DigitalTwin_InterfaceClient_SetCommandsCallbacks failed. error=<%s>", MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, result));
        SensorInterface_Close(interfaceHandle);
        interfaceHandle = NULL;
    }

    else
    {
        LogInfo("SENSOR_INTERFACE: Created DIGITALTWIN_INTERFACE_CLIENT_HANDLE successfully for interfaceId=<%s>, interfaceInstanceName=<%s>, handle=<%p>", SensorInterfaceId, SensorInterfaceInstanceName, interfaceHandle);
        appState.interfaceClientHandle = interfaceHandle;
    }

    return interfaceHandle;
}

void SensorInterface_Close(DIGITALTWIN_INTERFACE_CLIENT_HANDLE digitalTwinInterfaceClientHandle)
{
    // On shutdown, in general the first call made should be to DigitalTwin_InterfaceClient_Destroy.
    // This will block if there are any active callbacks in this interface, and then
    // mark the underlying handle such that no future callbacks shall come to it.
    DigitalTwin_InterfaceClient_Destroy(digitalTwinInterfaceClientHandle);

    // After DigitalTwin_InterfaceClient_Destroy returns, it is safe to assume
    // no more callbacks shall arrive for this interface and it is OK to free
    // resources callbacks otherwise may have needed.

    if (appState.wifimac != NULL)
    {
        free(appState.wifimac);
        appState.wifimac = NULL;
    }

    if (appState.lanmac != NULL)
    {
        free(appState.lanmac);
        appState.lanmac = NULL;
    }

}
